### ISSUE TITLE
Use computed CSS values instead of `element.style`

### ISSUE THREAD

**Issue by EmilePerron** [liflab/dom-pp#10]
## Explanation
The functions that rely on `element.style` are bound to return incorrect values for most elements, as it does not take into account styles that come from an external stylesheet or a `<style>` tag.

These should be updated to use [`window.getComputedStyle()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle).

Here's a list of functions that I found to rely on `element.style`:
- `BackgroundColor`
- `Color`
- `MarginTop`
- `MarginBottom`
- `MarginRight`
- `MarginLeft`
- `PaddingTop`
- `PaddingBottom`
- `PaddingRight`
- `PaddingLeft`
- `FontSize`

## How to reproduce
Get the H1's text color on the provided HTML:
```html
<html>
	<head>
		<style>
			h1 { color: red; }
			h1.heading { color: green; }
		</style>
	</head>
	<body>
		<h1 class="heading">Welcome to my sample page</h1>
		<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur veniam nemo repellendus provident adipisci eligendi eius repellat ab, voluptates numquam expedita autem est tempora praesentium laborum dolores quam facilis distinctio!</p>
	</body>
</html>
```

**Expected value:** `"green"` (or `#008000`)
**Current value:** `""`

**Comment by sylvainhalle** [comment]
The best way to fix this would be:

1. Write a test case that fails in this situation
2. Fix the issue and make sure that the test passes

One for each function, of course. ;-)
