### ISSUE TITLE
Fix ESLint warnings

### ISSUE THREAD

**Issue by sylvainhalle** [liflab/dom-pp#15]
Run `npm run lint` and see the file `eslint.html` for information

**Comment by ppalioune** [comment]
there are two warnings that i can't resolve.  Can you check it:
```
[-] C:\Users\Ppalioune\Desktop\apprentissagee\koalati\dom-pp\modules\designator.mjs1 problem (1 error, 0 warnings)
74:21 | Error | Parsing error: Unexpected token =
```
```
[-] C:\Users\Ppalioune\Desktop\apprentissagee\koalati\dom-pp\index.mjs2 problems (2 errors, 0 warnings)
95:14 | Error | 'dataTree' is not defined.
```

**Comment by EmilePerron** [comment]
> there are two warnings that i can't resolve. Can you check it:
> 
> ```
> [-] C:\Users\Ppalioune\Desktop\apprentissagee\koalati\dom-pp\modules\designator.mjs1 problem (1 error, 0 warnings)
> 74:21 | Error | Parsing error: Unexpected token =
> ```
> 
> ```
> [-] C:\Users\Ppalioune\Desktop\apprentissagee\koalati\dom-pp\index.mjs2 problems (2 errors, 0 warnings)
> 95:14 | Error | 'dataTree' is not defined.
> ```

For the `Unexpected token =`, seems like this might help: https://stackoverflow.com/a/44626825/2327027

As for the `'dataTree' is not defined`, I think switching
```js
// DataTree for tree management
import "data-tree";
```
to 
```js
// DataTree for tree management
import dataTree from "data-tree";
```
will solve the issue.

**Comment by sylvainhalle** [comment]
@sylvainhalle check this on your side
