### ISSUE TITLE
instanceof vs. className

### ISSUE THREAD

**Issue by sylvainhalle** [liflab/dom-pp#17]
Replace this line with an `instanceof`. It should not change anything.

https://github.com/liflab/dom-pp/blob/b2aedec1ef8f3fe20fed7d065480e80375a664d4/index.mjs#L139

**Comment by sylvainhalle** [comment]
Unless mistaken, we decided to leave it like that?

**Comment by amadouba9** [comment]
@sylvainhalle,  Emile and I,  We changed the the writing of the condition. Now the condition is written like this 
''' if (isHtmlElement(designatedObject.getObject())) { ''' . We already presented it to you. We were waiting for your approuval to close the issues.

**Comment by sylvainhalle** [comment]
OK!
