### ISSUE TITLE
Fix @extends in doc

### ISSUE THREAD

**Issue by sylvainhalle** [liflab/dom-pp#19]
Some of the `@extends` annotations in the comments do not match the actual class declaration. See for example `Color`: https://liflab.github.io/dom-pp/jsdoc/modules_web-element.mjs.html#line169

Fix: go over the classes and make sure that the `@extends` declaration is correct

**Comment by ppalioune** [comment]
@sylvainhalle i think you don't have the latest version.  this version uses: `extends CssPropertyFunction`.
```javascript
class Color extends CssPropertyFunction{   
    constructor(){
        super("color")
    }
}
```
https://github.com/ppalioune/dom-pp/blob/main/modules/web-element.mjs

**Comment by amadouba9** [comment]
@ppalioune Prof @sylvainhalle is right, the @ extends comment is not correct. Let's talk about it in mattermost.
