### ISSUE TITLE
Implement additional functions

### ISSUE THREAD

**Issue by sylvainhalle** [liflab/dom-pp#6]
Using the functions already implemented as examples, it should be easy to create new functions that inherit from `AtomicFunction`.

## In `numbers.mjs`

Arithmetic operators (subtraction, multiplication, etc.)

## In `web-element.mjs`

Functions extracting various attributes of DOM elements (background color, margins L/R T/D, etc.)

These functions should come with their *unit tests*, again by taking example on the unit tests for the existing functions.

**Comment by ppalioune** [comment]
@sylvainhalle  if you have no others comments or suggestions, this issue can be closed...
