### ISSUE TITLE
Add @extends to JSDoc comments

### ISSUE THREAD

**Issue by sylvainhalle** [liflab/dom-pp#7]
In order for the `jsdoc` module to show the class hierarchy in the generated doc, the ancestor of a class must be specified in the JSDoc comment using the `@extends` annotation. See for example: https://github.com/liflab/dom-pp/blob/01688ef191699d9ab90efb90f9a73931fc6ec893/modules/booleans.mjs#L35

Task: add the missing annotations to the source code.

**Comment by sylvainhalle** [comment]
@amadouba9 Si cette tâche est complétée, il faudrait fermer l'_issue_

**Comment by amadouba9** [comment]
@sylvainhalle bien reçu
